sudo: required
services:
  - docker
env:
  globa:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_8ede7f2e3be9_key -iv $encrypted_8ede7f2e3be9_iv -in gc_service_account.json.enc -out ./gc_service_account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gc_service_account.json
  - gcloud config set project udemy-multi-k8s-gc
  - gcloud config set compute/zone us-central1-c	
  - gcloud container clusters get-credentials udemy-multi-k8s-2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t johnpolansky/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true johnpolansky/react-test npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master